version: '3.8'

services:
  maps3_image_mapper:
    build: 
      context: .  # Relative path to the Dockerfile directory
      dockerfile: image_mapper.Dockerfile     

    container_name: maps3_image_mapper
    network_mode: host      # Use host networking for ROS 2 DDS
    environment:
      - ROS_DOMAIN_ID=1       # Use the same domain ID for all nodes
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
    restart: always           # Restart on failure
    volumes:
      - /dev/shm:/dev/shm  # Mount shared memory
    stdin_open: true      # Keep STDIN open for interactive mode
    tty: true             # Allocate a pseudo-TTY for interactive mode


  maps3_image_sender:
    build: 
      context: .  # Relative path to the Dockerfile directory
      dockerfile: maps3_image_sender.Dockerfile        
    
    container_name: maps3_image_sender
    network_mode: host      # Use host networking
    environment:
      - ROS_DOMAIN_ID=1
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
    restart: always
    volumes:
      - /dev/shm:/dev/shm  # Mount shared memory
    stdin_open: true      # Keep STDIN open for interactive mode
    tty: true             # Allocate a pseudo-TTY for interactive mode
  
  maps3_photo_processor:
    build: 
      context: .  # Relative path to the Dockerfile directory
      dockerfile: maps3_photo_processor.Dockerfile        
    
    container_name: maps3_photo_processor
    network_mode: host      # Use host networking
    environment:
      - ROS_DOMAIN_ID=1
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
    restart: always
    volumes:
      - /dev/shm:/dev/shm  # Mount shared memory
    stdin_open: true      # Keep STDIN open for interactive mode
    tty: true             # Allocate a pseudo-TTY for interactive mode

  rqt:
    image: osrf/ros:humble-desktop
    network_mode: host
    environment:
      - ROS_DOMAIN_ID=1
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/shm:/dev/shm  # Mount shared memory
    command: >
      /bin/bash -c "source /opt/ros/humble/setup.bash &&
                    rqt"
    stdin_open: true      # Keep STDIN open for interactive mode
    tty: true             # Allocate a pseudo-TTY for interactive mode
